### ISSUE TITLE
Remove hover effect on scrollbars

### ISSUE THREAD

**Issue by sdzhurova** [mishantrop/reactScrollarea#3]
Hello,

I tried to edit the styles for `verticalContainerStyle ` and make the `opacity: 1`. 
The issue here is that `onHover` it replaces the styles with  `opacity: .6!important;`.
What is the way to remove the hover hardcoded styles?

Thank you.

**Comment by mishantrop** [comment]
Thanks for using. 
"!important" removed.
Fresh demo might help: https://mishantrop.github.io/reactScrollareaDemo/
